### ISSUE TITLE
Does this package supports Typescrpt

### ISSUE THREAD

**Issue by st-clair-clarke** [msalehisedeh/wizard-storage#1]
Hi, Does this package supports Typescript?

**Comment by msalehisedeh** [comment]
It is On Angular 6 and written in typescript.

**Comment by msalehisedeh** [comment]
upgraded to angular 8. Sorry for it taking too long. i finally ported all my components to Mac OS. will continue porting all other components i have to angular 8.
Please let me know if i can be of help.

**Comment by msalehisedeh** [comment]
upgraded to angular 8.
