### ISSUE TITLE
Upgrading to angular 9

### ISSUE THREAD

**Issue by st-clair-clarke** [msalehisedeh/wizard-storage#2]
I really would like to use your package in my "@angular/cli": "^9.0.0-rc.6", application. However, it is not compatible.

Do you plan an upgrade soon.

Each time I inject the local storage in my application via the constructor it crashes with the following error
`
client:150 [WDS] Errors while compiling. Reload prevented.
errors @ client:150
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:888
SockJS._transportMessage @ sockjs.js:886
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2962
wrapFn @ zone-evergreen.js:1202
invokeTask @ zone-evergreen.js:400
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:481
invokeTask @ zone-evergreen.js:1596
globalZoneAwareCallback @ zone-evergreen.js:1622
client:159 J:/workspace/nrwl/pim/node_modules/@sedeh/wizard-storage/__ivy_ngcc__/fesm2015/sedeh-wizard-storage.js 309:29-53
"export 'ɵsetClassMetadata' (imported as 'ɵngcc0') was not found in '@angular/core'...
`

**Comment by msalehisedeh** [comment]
please give me a few days. will an upgrade to angular 8 make it compatible for you? i will upgrade to angular 8 first and letsa see if it works for you first.

**Comment by st-clair-clarke** [comment]
Angular 8 will be just fine. And thanks.

**Comment by msalehisedeh** [comment]
I have not forgotten about you. trying to move all my components to angular 8 and my code is on windows laptop. getting rid of node_modules directory is a nightmare. will move my code to Mac OS as soon as I can to save precious time. will deliver what you need as soon as i can. thanks.

**Comment by st-clair-clarke** [comment]
Thanks

**Comment by msalehisedeh** [comment]
upgraded to angular 8. please try it and let me know if all goes well.

**Comment by st-clair-clarke** [comment]
Upgrade working just fine. Great gift for the holidays!
