### ISSUE TITLE
REQUEST | Setting default values

### ISSUE THREAD

**Issue by st-clair-clarke** [msalehisedeh/wizard-storage#3]
After the holidays I would love if you could allow your storage to set default values, and load them to the store once present.

For many applications, similar to what I am developing currently, it include rage of values - upper limit, lower limit for each value. I could set generally acceptable defaults so that when the application executes these default would be used. Once the user set their precise values, the storage would use them instead.

So, even if the storage is cleared, the defaults should remain to repopulate the store on first run with keys that have no values.

Another important factor would be enrypting/decrypting storage.

Have a great holiday!
Please let me know what you think.

Cheers

**Comment by msalehisedeh** [comment]
sure thing. can you send me examples of how you would call methods and what would be expected of each method? I have it all on Mac OS now. can have it done really fast.

**Comment by st-clair-clarke** [comment]
Merry Christmas Masound! ie if you do celebarate Christmans. I see you have implemented encryption and default in the recently released version. Thanks.

I am checking it out right now!

**Comment by st-clair-clarke** [comment]
Thanks. Second best gift I receive this holidays! Thanks. I will be making more suggestions in the future. I would like your package to be the defacto standard for web storage.

**Comment by st-clair-clarke** [comment]
I have observed something a bit peculiar.

While attempting to use the default option  in getItem(), this is what is happening.

With no value in the local storage, the following works as expected on the first run of the component :

```
 this.areaCode = this._storage.local.getItem( 'areaCode', { default: '876' } )
console.log(this.areaCode) // prints 876
```

However, on subsequent runs of the component

```
console.log(this.areaCode) // prints undefined
```

I would expect on all runs for 876 to be printed since 876 is IN the store.

Let me know what you think.

Cheers

**Comment by msalehisedeh** [comment]
not clear the path you take in your component to get the areaCode. and the second path to log it the second time.

**Comment by msalehisedeh** [comment]
your feedback would me my gift.

**Comment by msalehisedeh** [comment]
there was a bug in retreival of secured content. try it again with varsion 2.1.1

**Comment by st-clair-clarke** [comment]
Hi Masoud,
Something you changed in version 2.1.1 causing a problem with "@angular/cli": "^9.0.0-rc.7 (no change in this and associated packages)

After updating to the current package and attempting to serve the app, here is the error

```
../../libs/common/registration-ui/src/lib/components/phone/phone.component.ts:18:38 - error TS2307: Cannot find module '@sedeh/wizard-storage'.

18 import { WizardStorageService } from '@sedeh/wizard-storage
```

The error occurs as Ivy attempts to compile the involved packages.

**Comment by st-clair-clarke** [comment]
I had also updated "rxjs": "^6.5.3" -> "rxjs": "^6.5.4"

Uncertain if your package dependency was broken.

**Comment by st-clair-clarke** [comment]
Reverted to version 2.1.0 with the updated rxjs package and everything works fine. It seems that the issue lies with the updated 2.1.1 version. I will wait for you to check it out.

**Comment by msalehisedeh** [comment]
something was wrong with my compilation. Had problem in stackblitz to render anything at all. i thought it was because of stackblitz CDN propagation, but it was not. i added 2.1.2 version and i can see it working again. please go to 2.1.2.

**Comment by msalehisedeh** [comment]
i had to re-package it. that was all. do not know what i did wrong. may be i was sleepy around the time i was doing it.

**Comment by st-clair-clarke** [comment]
Everything is working fine now. Thanks. Appreciate everything.

**Comment by msalehisedeh** [comment]
no problem. please keep the feedbacks coming. hope i can be of further help with this component and my other components as well.
